till/easybib-cookbooks

easybib-deploy/recipes/ssl-vagrant.rb
easybib-deploy/templates/default/nginx-ssl.conf.erb

references https://github.com/easybib/issues/issues/3014

Add ssl support in vagrant env

---

avahi/recipes/alias.rb

(h/t to @cameronprattedwards for researching this)

Fixes Avahi-Aliases: Install docutils

---

easybib-deploy/recipes/ssl-vagrant.rb

fixes https://github.com/easybib/issues/issues/3055

Bugfix (Typo): Use nginx-app, not nginx-lb, for apps

---

easybib-deploy/recipes/silex.rb

Its random right now which app appears when the webserver is being accessed via its ip
This PR makes sure scholar / discover-api is default

Bugfix: Make sure correct app listens on ip

---

easybib-deploy/recipes/ssl-certificates.rb
haproxy/attributes/customize.rb
haproxy/templates/default/haproxy.cfg.globals.erb

SSL Improvements and fixes for HAproxy

---

haproxy/templates/default/haproxy.easybib.cfg.erb

references easybib/issues#3116
Bugfix: Change health_check_string in haproxy.cfg.backend.erb to health_check

bugfix: Corrected health check variable name

---

haproxy/attributes/customize.rb
haproxy/templates/default/haproxy.cfg.frontend.erb

fixes https://github.com/easybib/issues/issues/3118

Feature: Add hsts header to haproxy

---

nginx-app/templates/default/easybib.com.conf.erb
nginx-app/templates/default/infolit.conf.erb
nginx-app/templates/default/silex.conf.erb

references https://github.com/easybib/issues/issues/2978

Feature: Add browser caching partial to EasyBib, InfoLit and Silex

---

ezproxy/templates/default/config.txt.erb

references https://github.com/easybib/issues/issues/3139

Feature: Improve ezproxy config

---

easybib-deploy/templates/default/nginx-ssl.conf.erb

fixes https://github.com/easybib/issues/issues/3424
see also http://api.symfony.com/2.3/Symfony/Component/HttpFoundation/Request.html#method_isSecure
cc @marsch

Add https header to vagrant nginx ssl config

---

easybib-deploy/recipes/silex.rb

references https://github.com/easybib/issues/issues/3731

Adding scholar admin to silex-role

---

.travis.yml

"real" fix in https://github.com/till/easybib-cookbooks/pull/588

Quickfix for travis artifacts upload

---

.travis.yml

references https://github.com/easybib/issues/issues/3749
This should fix it, but will obviously only be tested on merge

Fix travis artifact upload

---

easybib/recipes/role-easybib-housekeeping.rb

Add php-intl to housekeeping

---

pecl-manager/providers/script.rb

This is a minor fix for https://github.com/easybib/issues/issues/3042
I am not 100% sure of the syntax or if the check for vagrant is required (possibly since I am statically referencing the URI for the existence of autoload.php).

Fix for race condition on #3042

---

easybib/recipes/role-lb.rb
haproxy/attributes/customize.rb
haproxy/templates/default/haproxy.cfg.frontend.erb
haproxy/templates/default/haproxy.easybib.cfg.erb

* Do not deploy nginx-ssl with haproxy 1.5
* Make default haproxy layer name customizable

haproxy 1.5 fixes

---

.travis.yml
easybib-deploy/recipes/easybib.rb
easybib/attributes/default.rb
easybib/libraries/easybib.rb
easybib/providers/deploy.rb

* also deploys public api on housekeeping
* fix in travis.yml to speed up tests by about 40s
https://github.com/easybib/issues/issues/3805

Allow stack.json configuration of housekeeping role

---

nginx-app/templates/default/easybib.com.conf.erb

@till LMK what you think.. seems to work when I do `http://easybib.bib/vmntribes-vast-tag/`
Re: https://github.com/easybib/issues/issues/3931#issuecomment-94958679

add vast tag

---

easybib/recipes/role-generic.rb
easybib/recipes/role-nginxapp-infolit.rb
easybib/recipes/role-phpapp.rb

Update: move supervisor into generic

---

easybib/providers/supervisor.rb
easybib/spec/easybib_supervisor_spec.rb

Hopefully fixes: easybib/researchready#2408 easybib/researchready#2410

Fix: always restart supervisor

---

nginx-app/recipes/vagrant-silex.rb

Related: easybib/issues#3899, easybib/scholar#1002

Enhancement: enable supervisor in vagrant

---

easybib-deploy/recipes/easybib-housekeeping.rb

This has to go in stable
references https://github.com/easybib/issues/issues/3805

Fix: Mixed up layer name and app name

---

nginx-app/templates/default/easybib.com.conf.erb

Need to still test locally and run nginx configtest

change seconds to 5 on all proxy timeouts

---

percona/attributes/default.rb
percona/recipes/client.rb
percona/recipes/repository.rb
percona/recipes/server.rb

* adds support for Percona Server 5.6 (aka MySQL 5.6)
* refactorings/improvements to use attributes and avoid hardcoding
cc @glaubinix

Percona recipe improvements

---

nginx-app/recipes/vagrant-silex.rb

Fix: generate deploy config before it's used

---

easybib/libraries/easybib.rb
easybib/recipes/role-phpapp.rb

* see bash, composer, etc. cookbooks
* broke it with #636

Update/Fix: respond with nil values to be consistent

---

VERSIONS.md
chef_handler_sns/files/default/body_template
chef_handler_sns/recipes/default.rb

Adds Stack Name to the notification email

Add stack name to chef_handler_sns notification

---

haproxy/recipes/configure.rb

fixes https://github.com/easybib/issues/issues/3450

Reload haproxy on template change

---

sinopia-github/templates/default/config.yaml.erb

changing config template from:
allow_access: admin $authenticated
to:
allow_access: admin $authenticated <%= @admins.join(' ') %>

Fix the config.yml template to allow admin users access

---

nginx-app/templates/default/infolit.conf.erb

Fix: Serve intermediate certificates for academy

---

easybib/libraries/ppa.rb
easybib/tests/test_ppa.rb

also tests to prevent this from happening again

Bugfix for missing ppa_mirror param

---

easybib-deploy/recipes/silex.rb

fixes https://github.com/easybib/issues/issues/4475

Make api the default server, not id

---

.rubocop.yml
nginx-app/templates/default/nginx.conf.erb
rails/libraries/rails_configuration.rb

references https://github.com/aws/opsworks-cookbooks/pull/234

Enables opsworks rails layer to work with our Ubuntu setup

---

easybib/recipes/role-nginxapp-publicapi.rb

references https://github.com/easybib/issues/issues/3805

Always use redis receipe instead of package

---

supervisor/attributes/default.rb

https://github.com/easybib/issues/issues/4482

make supervisor socket world readable

---

easybib-deploy/recipes/ssl-certificates.rb
easybib-deploy/spec/ssl-certificates_spec.rb
easybib/providers/sslcertificate.rb
easybib/recipes/role-nginxapp-redirector.rb
easybib/resources/sslcertificate.rb
nginx-app/recipes/redirector-ssl.rb
nginx-app/spec/redirector_ssl_spec.rb
nginx-app/templates/default/redirect-ssl.conf.erb

references https://github.com/easybib/issues/issues/4531

Add support for ssl redirector

---

easybib-deploy/attributes/default.rb
easybib-deploy/recipes/easybib.rb
easybib-deploy/recipes/infolit.rb
easybib-deploy/recipes/internal-api.rb
easybib-deploy/recipes/qa.rb
easybib-deploy/recipes/research.rb
easybib-deploy/recipes/scholar.rb
easybib-deploy/recipes/silex.rb
easybib/attributes/default.rb

* move deploy action into the recipe where it belongs
* make it configurable for all deploys
Related: easybib/issues#4597

Refactor: deploy_action

---

nginx-app/spec/silex-template_spec.rb
nginx-app/templates/default/partials/php-routes-specific-routes.erb

This fixes easybib/issues#4748.

Less permissive Nginx location

---

postfix/attributes/default.rb

References: https://github.com/easybib/issues/issues/4774

add mailer-daemon and www-data to /etc/aliases

---

nginx-app/attributes/default.rb
nginx-app/libraries/helpers.rb
nginx-app/recipes/configure.rb
nginx-app/spec/configure_spec.rb
nginx-app/templates/default/easybib.com.conf.erb
nginx-app/templates/default/partials/module-assets.erb
nginx-app/templates/default/partials/status-checks.erb
nginx-app/tests/test_helpers.rb

Not the ones we are already dealing with in the caching section anyway
references easybib/issues#4602 (comment)

Only prevent unhandled static extensions from php  handling

---

easybib/libraries/easybib.rb
easybib/libraries/sns.rb
easybib/recipes/setup.rb

First try to get this running.

Implement load-based spin-up notifications via SNS

---

easybib-deploy/recipes/scholar.rb
easybib/libraries/easybib.rb
easybib/tests/test_easybib.rb

fixes https://github.com/easybib/issues/issues/4810

Feature: Allow multiple requested roles for allow_deploy

---

easybib/attributes/default.rb
easybib/libraries/easybib.rb
easybib/libraries/sns.rb
easybib/recipes/setup.rb

In regards to: https://github.com/easybib/issues/issues/4573

Fix SNS Notify

---

nginx-app/templates/default/easybib.com.conf.erb

fixes https://github.com/easybib/issues/issues/4837

Bypass php for /raw/

---

haproxy/recipes/ctl.rb

Use the EasyBib fork of haproxyctl

---

scholar/recipes/role-vagrant-erlang.rb

to compile jiffy (JSON parser)

erlang VM needs build-essential

---

nginx-app/recipes/service.rb

* stop nginx via upstart (when config exists)
* remove upstart config
* start nginx via debian/init from then on
Related: easybib/issues#4836

Update: migrate

---

nginx-app/recipes/redirector.rb
nginx-app/templates/default/redirect.conf.erb

https://github.com/easybib/issues/issues/4285

Add second redirector possibilty

---

scholar/recipes/role-vagrant.rb

Fix: install a compiler (for npm)

---

haproxy/attributes/customize.rb
haproxy/templates/default/haproxy.cfg.frontend.erb
nginx-app/recipes/redirector.rb
nginx-app/templates/default/redirect.conf.erb

Mainly due to: https://github.com/easybib/issues/issues/4819

Stable chef 11.10

---

apache-couchdb/attributes/default.rb

this is not yet tested, but should work according to the docs:
https://wiki.apache.org/couchdb/Compaction#Automatic_Compaction
references https://github.com/easybib/issues/issues/4947

Enable compaction daemon

---

tideways/recipes/default.rb

Update: install tideways-cli

---

haproxy/files/default/scholar/5xx.http

fixes https://github.com/easybib/issues/issues/4983

Fix: Wording and support link changed

---

postfix/attributes/default.rb
postfix/recipes/aliases.rb
postfix/recipes/default.rb
postfix/recipes/relay.rb
postfix/templates/default/main.cf.erb
postfix/templates/default/passwd.erb

* Add mail relaying if relay is set in config
* Bugfix: Use internal ip adress directly, do not resolve
* Bugfix: Do not create mailforward if sysadmin mail is nil
* Bugfix: Do not create relaying if no relayhost is set

Postfix: Improvements and bugfixes

---

postfix/recipes/relay.rb
postfix/templates/default/main.cf.erb

Only as a first step, this is something where we can add the other instance hostnames later

Fixes mydestination value for postfix

---

postfix/attributes/default.rb
postfix/recipes/aliases.rb
postfix/templates/default/aliases.erb

Fix mail-alias routing problems

---

haproxy/recipes/ctl.rb

Explictly call cron-job via Bash

---

scholar/recipes/role-erlang.rb
scholar/recipes/role-vagrant-erlang.rb
scholar/recipes/role-vagrant.rb

Install and start supervisor on all scholar instances

---

easybib-deploy/recipes/scholar.rb
easybib-deploy/recipes/silex.rb
scholar/recipes/role-phpapp.rb
scholar/recipes/role-scholar.rb

fixes https://github.com/easybib/issues/issues/5033
fixes https://github.com/easybib/issues/issues/5034
needs merge into stable

Fix: scholar admin no longer standalone

---

statsd/spec/configure_spec.rb
statsd/templates/default/easybib-config.js.erb

Fix: delete idle stats

---

.rubocop.yml
VERSIONS.md
route53/.gitignore
route53/.kitchen.yml
route53/.rspec
route53/.travis.yml
route53/CHANGELOG.md
route53/Cheffile
route53/Gemfile
route53/Guardfile
route53/README.md
route53/Rakefile
route53/attributes/default.rb
route53/libraries/matchers.rb
route53/metadata.rb
route53/providers/record.rb
route53/recipes/default.rb
route53/resources/record.rb
route53/spec/default/default_spec.rb
route53/spec/spec_helper.rb
route53/test/integration/cookbooks/route53_test/README.md
route53/test/integration/cookbooks/route53_test/metadata.rb
route53/test/integration/cookbooks/route53_test/recipes/default.rb
route53/test/integration/default/serverspec/default_spec.rb
route53/test/integration/default/serverspec/spec_helper.rb

Issue: easybib/issues#5085
----
This PR pulls in the cookbook https://github.com/hw-cookbooks/route53.

Introduce hw-route53 cookbook

---

ies-route53/recipes/add.rb
ies-route53/spec/add_spec.rb
ies-route53/spec/spec_helper.rb

* add a spec for this fix
* remove is_aws wrap from LWRP call

Update: fix is_aws call in route53_record

---

nginx-app/spec/silex-template_spec.rb
nginx-app/templates/default/partials/status-checks.erb
php-fpm/templates/default/pool.conf.erb

Fix: make fpm_status & fpm_ping work again

---

easybib/recipes/role-nginxapp-infolit.rb
easybib/recipes/role-nginxapp-research.rb

fixes regression in https://github.com/till/easybib-cookbooks/pull/760
references https://github.com/easybib/researchready/issues/4182#issuecomment-157308202

Fix: Supervisor for infolit

---

easybib-deploy/recipes/scholar.rb
easybib/providers/deploy.rb
easybib/providers/supervisor.rb

Does not change anything, makes debugging easier

Cleanup: Relocate the default value override in the actual provider

---

apache-couchdb/recipes/monitoring.rb
bibcd/providers/app.rb
easybib-deploy/recipes/qa.rb
easybib/libraries/config.rb
easybib/libraries/easybib.rb
easybib/libraries/php.rb
easybib/providers/nginx.rb
easybib_vagrant/libraries/helpers.rb
easybib_vagrant/recipes/configure.rb
easybib_vagrant/recipes/cookbooks.rb
haproxy/recipes/ctl.rb
ies-mysql/recipes/dev.rb
ies-route53/recipes/add.rb
nginx-app/recipes/configure.rb
nginx-app/recipes/vagrant.rb
php-fpm/libraries/helper.rb
postfix/recipes/mailname.rb

Refactor: move chef::foo.include() into lib

---

.travis.yml
Rakefile
ies-route53/spec/spec_helper.rb

time before 1m51.107s
time after 0m21.640s
Also removes annyoing test noise introduced with route53

Refactored foodcritic handling: Speeed

---

.gitignore
nginx-amplify/README.md
nginx-amplify/attributes/default.rb
nginx-amplify/files/default/uuid.py
nginx-amplify/libraries/helper.rb
nginx-amplify/metadata.rb
nginx-amplify/recipes/configure.rb
nginx-amplify/recipes/default.rb
nginx-amplify/recipes/service.rb
nginx-amplify/spec/configure_spec.rb
nginx-amplify/spec/default_spec.rb
nginx-amplify/spec/spec_helper.rb
nginx-amplify/templates/default/agent.conf.erb

Enhancement: first pass on a cookbook for nginx-amplify

---

easybib/libraries/sns.rb

Fix: require aws-sdk later

---

php/recipes/dependencies-ppa.rb

Issue: None.
Related: https://imagineeasy.atlassian.net/browse/DEVOPS-18

Remove duplicate include_recipe

---

bash/spec/bashrc_spec.rb
easybib-deploy/spec/infolit_spec.rb
easybib-deploy/spec/nginx-internalapi_spec.rb
easybib-deploy/spec/ssl-certificates_spec.rb
easybib/spec/spec_helper.rb

Fix: Readjust chefspec loglevel

---

easybib/recipes/role-vagrant-www.rb

Fix: xdebug breaks tideways postinst

---

easybib/libraries/easybib.rb

Improvement: Return "vagrant" as stackname in vagrant

---

nginx-app/attributes/default.rb
nginx-app/metadata.rb
nginx-app/recipes/rsyslogs.rb
nginx-app/recipes/server.rb
nginx-app/resources/config.rb
nginx-app/templates/default/nginx-rsyslog.erb

https://imagineeasy.atlassian.net/browse/DEVOPS-71

DEVOPS-71 - logging through to rsyslog via /dev/log

---

.travis.yml

https://imagineeasy.atlassian.net/browse/DEVOPS-59

Add webhook to trigger cookbook updates

---

easybib_vagrant/attributes/default.rb
easybib_vagrant/providers/user.rb
easybib_vagrant/templates/default/bash-profile.erb
virtualbox/recipes/default.rb

* Fixes `.bash_profile` permissions
* Fixes vagrant plugins installation
* Fixes keychain installation
* Silences keychain output
* Adjusts list of vagrant plugins to the actually used list
* installs current kernel headers (needed by virtualbox)

Fixes & improvements for vagrant ci

---

ies-route53/recipes/add.rb

Jira: https://imagineeasy.atlassian.net/browse/DEVOPS-104

[WIP] F/ies-route53-respect-eips

---

ies-mysql/recipes/default.rb
ies-mysql/templates/default/vagrant-user.cnf.erb

super hacky investigating https://imagineeasy.atlassian.net/browse/DEVOPS-98

Hack to users mysql config to hit mysql without cmdln opts

---

easybib-deploy/recipes/internal-api.rb

references https://github.com/easybib/sbm-issues/issues/183
references https://github.com/easybib/sbm-issues/issues/182

Add support for generic citation api app

---

ies-mysql/recipes/default.rb

referencing https://imagineeasy.atlassian.net/browse/DEVOPS-98
adding support for ~/.my.cnf in hacky way for root

DEVOPS-98 take II, now with root support

---

easybib-deploy/recipes/opsworks-sample.rb
stack-test/README.md
stack-test/metadata.rb
stack-test/recipes/role-sample.rb

Update: stack-test

---

easybib/providers/supervisor.rb
easybib/resources/supervisor.rb
ies/recipes/role-undeploy.rb

References: JIRA [DEVOPS-88](https://imagineeasy.atlassian.net/browse/DEVOPS-88)

Undeploy of supervisor - DEVOPS-88

---

easybib/providers/supervisor.rb

References: JIRA [DEVOPS-88](https://imagineeasy.atlassian.net/browse/DEVOPS-88)

t/supervisorcleanup Supervisord cleanup of processes no longer needed

---

stack-easybib/libraries/helpers.rb
stack-easybib/recipes/deploy-easybib.rb
stack-easybib/recipes/role-nginxapp.rb
stack-easybib/recipes/role-phpapp.rb
stack-easybib/templates/default/easybib.com.conf.erb

- move all deploy-* recipes to cookbook
- move all templates to cookbook
- no longer use nginx-app::configure

No longer use nginx-app::configure in stack-easybib

---

stack-easybib/libraries/helpers.rb
stack-easybib/recipes/deploy-easybib.rb
stack-easybib/spec/role-nginxapp_spec.rb
stack-easybib/spec/spec_helper.rb
stack-easybib/templates/default/easybib.com.conf.erb

Fix: Broken merge_alias_config call

---

easybib/libraries/deploy.rb
easybib/libraries/matchers.rb
easybib/providers/deploy_manager.rb
easybib/resources/deploy_manager.rb
easybib/spec/easybib_deploy_manager_spec.rb
easybib/spec/fixtures/attributes/default.rb
easybib/spec/fixtures/metadata.rb
easybib/spec/fixtures/recipes/easybib_deploy_manager.rb
easybib/spec/fixtures/recipes/easybib_deploy_manager_broken_apps.rb
stack-academy/attributes/default.rb
stack-academy/recipes/deploy.rb
stack-academy/spec/deploy_spec.rb

Refactor: deploy handling

---

vagrant-test/postfix/.gitignore
vagrant-test/postfix/Vagrantfile
vagrant-test/postfix/amazon-ses.json-dist

Update: test setup for SES

---

haproxy/spec/backend_forwarding-backends_spec.rb
haproxy/spec/backend_healthcheck_spec.rb
haproxy/spec/websocket_spec.rb
monit/recipes/systemcheck.rb

Refactor: use dns name

---

postfix/recipes/relay.rb
postfix/recipes/service.rb
postfix/templates/default/generic.erb
postfix/templates/default/header_check.erb
postfix/templates/default/main.cf.erb

* rewrite certain headers for Amazon SES
* add more catch-all rewrites using generic
* refactor service logic/notifications
Related: DEVOPS-139

Enhancement: rewrite all the things

---

easybib/providers/deploy_manager.rb
easybib/spec/easybib_deploy_manager_spec.rb
stack-scholar/attributes/default.rb
stack-scholar/recipes/deploy.rb
stack-scholar/spec/bugs_spec.rb
stack-scholar/spec/deploy_spec.rb
stack-scholar/spec/fixtures/brokenapps.json
stack-scholar/spec/fixtures/deploy.json
stack-scholar/spec/fixtures/metadata.rb
stack-scholar/spec/fixtures/recipes/brokenapps.rb

Refactor: move scholar to easybib_deploy_manager

---

php/attributes/default.rb
php/metadata.rb
php/recipes/dependencies-ppa.rb
php/spec/dependencies-ppa_spec.rb

* allow override of ppa values via node attributes
* updates tests and dependencies to reflect that
Related: DEVOPS-124

Refactor: allow php to setup ppa

---

php/attributes/default.rb
php/recipes/module-apc.rb
php/recipes/module-mysqli.rb
php/recipes/module-opcache.rb
php/recipes/module-phar.rb
php/recipes/module-soap.rb
php/recipes/module-tidy.rb
php/recipes/module-xdebug.rb
php/spec/module-apc_spec.rb
php/spec/module-soap_spec.rb

Set of initial default loadpriorities

---

php/providers/config.rb
php/spec/provider-config_spec.rb

Add rjust to load_priority format in php:config

---

stack-easybib/templates/default/easybib.com.conf.erb

Jira: https://imagineeasy.atlassian.net/browse/DEVOPS-146
GH: https://github.com/easybib/sbm-issues/issues/314

Add alias location for crossdomain.xml

---

php/recipes/module-phar.rb
php/recipes/module-zlib.rb

* php5-easybib has packages for this
* new php comes with these compiled in
From: #984
Related: DEVOPS-124

Update: phar/zlib are included in new PHP

---

stack-academy/recipes/role-nginxphpapp.rb
stack-academy/recipes/role-vagrant.rb

Related: easybib/researchready#5234

Enhancement: install wkhtmltopdf

---

easybib/providers/deploy_manager.rb
easybib/spec/easybib_deploy_manager_spec.rb
stack-academy/attributes/default.rb

Refactor: support for cookbook on easybib_nginx

---

easybib/providers/nginx.rb
nginx-app/attributes/default.rb
nginx-app/libraries/helpers.rb
nginx-app/recipes/cache.rb
nginx-app/tests/test_helpers.rb
stack-easybib/attributes/default.rb

Jira: https://imagineeasy.atlassian.net/browse/DEVOPS-151

Fix name mismatch used for browser static caching

---

stack-service/attributes/default.rb
stack-service/metadata.rb
stack-service/recipes/role-rabbitmq.rb
stack-service/spec/role-rabbitmq_spec.rb

Jira: https://imagineeasy.atlassian.net/browse/DEVOPS-150

logrotate the rabbitmq logs

---

fakesqs/README.md
fakesqs/metadata.rb
fakesqs/recipes/default.rb
fakesqs/spec/default_spec.rb

Related to [DEVOPS-156](https://imagineeasy.atlassian.net/browse/DEVOPS-156) 
Dependency of  on https://github.com/till/easybib-cookbooks/pull/1028
Dependency of https://github.com/easybib/scholar-vagrant/pull/163

FakeSQS Chef Recipe for vagrant setup

---

stack-citationapi/recipes/deploy-vagrant.rb
stack-citationapi/recipes/role-formatting-api.rb
stack-citationapi/recipes/role-vagrant-publicapi.rb
stack-easybib/recipes/deploy-silexapps.rb
stack-easybib/recipes/deploy-webapps-vagrant.rb
stack-easybib/recipes/role-nginxapp.rb
stack-easybib/recipes/role-nginxphpapp.rb
stack-easybib/recipes/role-vagrant.rb
stack-easybib/spec/role-nginxapp_spec.rb
stack-easybib/spec/role-vagrant_spec.rb
stack-easybib/templates/default/silex.conf.erb

added edu and webeval, fixed public-api under vagrant bug

---

php-fpm/recipes/configure.rb
php-fpm/spec/configure_spec.rb
stack-scholar/recipes/deploy.rb

Relates to https://imagineeasy.atlassian.net/browse/DEVOPS-158

Chef modification to stack-scholar to ensure PHP-CLI is as chosen

---

stack-easybib/recipes/deploy-easybib.rb
stack-easybib/recipes/role-housekeeping.rb

Jira: https://imagineeasy.atlassian.net/browse/DEVOPS-154

Housekeeping for www

---

haproxy/templates/default/haproxy.cfg.frontend.erb

Introduced two variables for things that get used and used again
inside the template. Hopefully shorting lines, so we can break it
down into sub-templates later.

Refactor: use variables to make lines more readable

---

stack-easybib/recipes/deploy-webapps-vagrant.rb

Fixes: [DEVOPS-170](https://imagineeasy.atlassian.net/browse/DEVOPS-170) and https://github.com/easybib/sbm-issues/issues/459
Make sure www gets build after edu to have www deploy configuration available inside vagrant.

Easybib: adjust vagrant app setup order

---

stack-cmbm/recipes/deploy-nginxapp.rb
stack-cmbm/spec/deploy-nginxapp_spec.rb

Jira: https://imagineeasy.atlassian.net/browse/DEVOPS-169

Split CM and BM into separate layers

---

vagrant-test/php/index.php
vagrant-test/php/test

Test files I had sitting around.

Update: test files for vagrant php test

---

haproxy/templates/default/haproxy.cfg.frontend.erb
haproxy/templates/default/haproxy.cfg.globals.erb

Fix: move into backends

---

stack-easybib/recipes/role-vagrant.rb

Need fakesqs + supervisor setup before we try to setup workers else worker setup fails.

Easybib: setup supervisor + sqs before worker setup

---

haproxy/spec/ssl_spec.rb

Enhancements: tests for ssl config

---

easybib/spec/easybib_sslcertificate_spec.rb
easybib/spec/fixtures/recipes/easybib_sslcertificate.rb

Enhancement: add tests for easybib_sslcertificates

---

stack-api/spec/role-nginxphpapp_spec.rb
stack-api/spec/spec_helper.rb
stack-citationapi/spec/role-citation-internalapi_spec.rb
stack-citationapi/spec/role-citation-publicapi_spec.rb
stack-citationapi/spec/role-lb_spec.rb

Jira: https://imagineeasy.atlassian.net/browse/DEVOPS-161

Some missing tests for stack-* cookbooks

---

ies-mysql/spec/integration_spec.rb

Related till/easybib-cookbooks#1069

Update: add an integration test for cookbook mysql

---

stack-citationapi/recipes/deploy-citationapi.rb
stack-citationapi/spec/deploy-citationapi_spec.rb
stack-citationapi/spec/role-citation-pdf-api_spec.rb

Jira: https://imagineeasy.atlassian.net/browse/DEVOPS-168

PDF Autocite for Stack CitationAPI

---

.travis.yml
Gemfile
Makefile
stack-api/.gitignore
stack-citationapi/.gitignore
stack-cmbm/.gitignore
stack-easybib/.gitignore
stack-ops/.gitignore
stack-qa/.gitignore
stack-research/.gitignore
stack-service/.gitignore

Jira: https://imagineeasy.atlassian.net/browse/DEVOPS-23

Add berkshelf make-target

---

ies-mysql-tuning-primer/README.md
ies-mysql-tuning-primer/metadata.rb
ies-mysql-tuning-primer/recipes/default.rb

Introducing cookbook ies-mysql-tuning-primer

---

stack-wpt/recipes/role-vagrant.rb

Related: easybib/issues#5661, easybib/issues#5659

Update: install pandoc

---

php/providers/config.rb
php/spec/etc_spec.rb

Fix: ensure the ini files are enabled

---

php/libraries/matchers.rb
php/providers/pecl.rb
php/resources/pecl.rb

- this is not used currently
- this functionality should not be wrapped away
- this code duplicates php_config

Update: remove "setup" from php_pecl

---

stack-wpt/recipes/role-languagetool.rb
stack-wpt/recipes/role-libreoffice.rb
stack-wpt/recipes/role-vagrant.rb

- push setup code for tools into dedicated recipes
- re-order setup for java, libreoffice and lt
Related: easybib/issues#5721

Fix: sometimes things are not installed :trollface:

---

ies-mysql-tuning-primer/README.md
ies-mysql-tuning-primer/recipes/default.rb

* wrong config syntax
* needs mysql client package

Bugfixes for mysql tuning primer

---

stack-wpt/attributes/default.rb
stack-wpt/recipes/role-vagrant.rb
stack-wpt/spec/spec_helper.rb
stack-wpt/spec/vagrant_spec.rb

* refactors attribute magic into default file
* adds a basic test to ensure we don't break this too often
Related: till/easybib-cookbooks#1103

Refactor: move all node.set to attributes/default

---

stack-api/Berksfile
stack-api/Berksfile.lock
stack-citationapi/Berksfile
stack-citationapi/Berksfile.lock
stack-cmbm/Berksfile
stack-cmbm/Berksfile.lock
stack-easybib/Berksfile
stack-easybib/Berksfile.lock
stack-ops/Berksfile
stack-ops/Berksfile.lock
stack-qa/Berksfile
stack-qa/Berksfile.lock
stack-research/Berksfile
stack-research/Berksfile.lock
stack-service/Berksfile
stack-service/Berksfile.lock

- remove metadata directive from Berksfiles
- add all Berksfile.lock files to git
Issue: https://github.com/easybib/ops/issues/180

Refactor Berksfiles

---

stack-cmbm/recipes/deploy-vagrant.rb

related: https://github.com/easybib/citationmachine-bibme/pull/1131
https://github.com/easybib/ops/issues/186

Clean up and readjust socket handling in vagrnat

---

ies-gearmand/attributes/default.rb
ies-gearmand/spec/default_spec.rb

This unbreaks the PHP install.

Fix: this overwrote global PHP

---

stack-api/Berksfile
stack-citationapi/Berksfile
stack-cmbm/Berksfile
stack-easybib/Berksfile
stack-qa/Berksfile
stack-research/Berksfile
stack-service/Berksfile

Cleanup: Berksfile syntax

---

php/recipes/module-xdebug.rb

Ensures xdebug settings are installed into the correct path!

Fix: ensure the settings are installed into the correct path

---

wt-data/libraries/dataobject.rb

Preparation for Chef12. No change to Chef11 runs.

Add database object for chef12 runs

---

CONTRIBUTING.md
Makefile
gemfiles/chef_11.10.gemfile
gemfiles/chef_11.10.gemfile.lock
gemfiles/chef_12.7.gemfile
gemfiles/chef_12.7.gemfile.lock

Adds `make install` to remember less commands to type.
- _(if applicable) how to test them_
Related: #issue

Update: introduce `make install`

---

easybib/providers/deploy.rb
easybib/resources/supervisor.rb
easybib/spec/fixtures/recipes/easybib_supervisor_create_with_orphan.rb
easybib/spec/fixtures/recipes/easybib_supervisor_disable.rb
easybib/spec/fixtures/recipes/easybib_supervisor_explicit_attributes.rb
easybib/spec/fixtures/recipes/easybib_supervisor_implicit_attributes.rb
easybib/spec/fixtures/recipes/easybib_supervisor_without_matching_role.rb
ies/recipes/role-undeploy.rb
nginx-app/recipes/vagrant-silex.rb
stack-citationapi/recipes/deploy-vagrant.rb
stack-citationapi/spec/role-sitescraper_spec.rb
stack-easybib/recipes/deploy-webapps-vagrant.rb
stack-scholar/recipes/deploy-silex-vagrant.rb

Related: https://github.com/easybib/ops/issues/233

Cleanup: Remove redundant app name

---

wt-data/libraries/dataobject.rb

Fixes https://github.com/easybib/ops/issues/241

Bugfix: Domains should not be nil

---

easybib/libraries/config.rb

Codeclimate is right, this is was a bit messy.

Cleanup: Split up envconfig function

---

php-fpm/recipes/monit.rb
php-fpm/recipes/prepare.rb
php-fpm/recipes/service.rb

* removes duplicate/faulty init.d script
* updates monit with a restart command
Related: easybib/ops#243

Fix: service name when we use ondreij PPA

---

.rubocop.yml
easybib/libraries/config.rb
easybib/libraries/easybib.rb
easybib/libraries/sns.rb
easybib/providers/deploy_manager.rb
easybib/providers/nginx.rb
php/providers/pear.rb

* dbconfig
* hostname
* nginx htpasswd
Related: https://github.com/easybib/ops/issues/233

Simplify methods in libraries

---

tideways/recipes/configure.rb

Removed empty if block.
Related: easybib/ops#251

Fix: install .ini

---

php/attributes/default.rb
php/recipes/module-sybase.rb
php/spec/module-sybase_spec.rb
php/templates/default/freetds.erb
stack-easybib/recipes/deploy-rdstest.rb
stack-easybib/recipes/role-vagrant.rb
stack-qa/recipes/deploy-redirector.rb
stack-qa/spec/deploy_redirector_spec.rb
stack-qa/templates/default/redirect-certbot.conf.erb
stack-qa/templates/default/redirect-ssl.conf.erb

* Fixed rds-test deps #1197
* Let's encrypt fixes, #1191 
* Enhancement: support for MS SQL Server, easybib/sbm-issues#841

Updating stable

---

php-fpm/recipes/configure.rb
stack-api/recipes/role-nginxphpapp.rb

* same PHP version (5.6)
* also adds sybase
- test on API Staging
Related: easybib/sbm-issues#841

Update: switch staging PHP to ondreij ppa

---

stack-api/recipes/role-nginxphpapp.rb

This PR pulls in php-zip.
Related: easybib/ops#259

[WIP] Install php-zip

---

stack-api/attributes/default.rb
stack-api/recipes/role-nginxphpapp.rb

- enables the PPA for "API" production 
Related: easybib/sbm-issues#841

Update: 5.6 on production

---

php-fpm/recipes/default.rb
php-fpm/spec/default_spec.rb

- Remove session cronjob, #1205

Stable merge

---

stack-citationapi/attributes/default.rb
stack-citationapi/recipes/role-phpapp.rb
stack-citationapi/spec/role-phpapp_spec.rb

Patch in Ondreij PPA for PHP in Citation-API stack.
Related: easybib/ops#218

Patch in ondrej ppa for Citation-API stack

---

stack-citationapi/recipes/role-phpapp.rb
stack-citationapi/spec/role-phpapp_spec.rb

I missed one PHP dependency to gearman.
Related: easybib/ops#218

Add missing gearman dep

---

aptly/attributes/default.rb

This PR adds the GPG-Key of recently added Ondrej PPA.
Related: easybib/ops#291

Add gpgkey for ondrej ppa

---

ies-letsencrypt/templates/default/certbot-cronjob.sh.erb

This PR fixes the renewal bug in our LetsEncrypt Cron-Script.
Related: easybib/ops#294

Fix LetsEncrypt renewal process

---

stack-easybib/attributes/default.rb
stack-easybib/recipes/role-phpapp.rb
stack-easybib/spec/role-nginxapp_spec.rb
stack-easybib/spec/role-phpapp_spec.rb

This PR patches `stack-easybib` to use the Ondrej PPA for PHP.
Related: easybib/ops#218

Ondrej PPA for stack-easybib

---

fake-sqs/recipes/default.rb

- use chef to maintain locked down dependencies
- we should probably look into fake_sqs as it seems orphaned
Fixes: easybib/ops#330

Fix: in absense of a Gemfile.lock and proper versions

---

nginx-app/attributes/default.rb
nginx-app/templates/default/nginx-rsyslog.erb

Fixed duplicated attribute "default['nginx-app']['access_log']"

Fixed duplicated attributes

---

stack-easybib/recipes/role-gearmanw.rb
stack-easybib/spec/role-gearmanw_spec.rb
stack-easybib/spec/spec_helper.rb

- adds a test case for the gearman worker cronjob
- adds a test on '\\'

Fix autocite cronjob (again)

---

ies-scout/metadata.rb
ies-scout/recipes/default.rb

- creates a user/group for scout (when no key is specified)
Related: OPS-14319

Bugfix: OPS-14319

---

stack-easybib/recipes/deploy-gearman-worker.rb

Fix: ensure pecl-manager is restarted

---

ies-scout/recipes/default.rb
scout/recipes/default.rb

- try to lock down nokogiri dependency
- add options to scout gem install to not update/upgrade anything
Related: OPS-14319

Fix: scout install

---

php-redis/attributes/default.rb
php-redis/recipes/default.rb

OPS-15568. Installing phpize

---

php-redis/attributes/default.rb
php-redis/recipes/default.rb

OPS-15568. Created symbol links to ini file

OPS-15568. Created symbol links to ini file

---

php/attributes/default.rb

OPS-15568. Added default attributes

OPS-15568. Added default attributes

---

php-redis/recipes/default.rb

OPS-15568. removed 7.2 dev
