nginx-lb/recipes/configure.rb

If we start/restart later, we could end up with being "stop" issued as the last command

Bugfix: Make sure we stop nginx immediately

---

easybib-deploy/attributes/default.rb
easybib-deploy/recipes/ssl-certificates.rb
easybib-deploy/recipes/ssl.rb
easybib/recipes/role-nginxapp-infolit.rb
haproxy/attributes/customize.rb
haproxy/recipes/default.rb
haproxy/templates/default/haproxy.cfg.frontend.erb
haproxy/templates/default/haproxy.cfg.globals.erb
monit/recipes/service.rb
nginx-lb/attributes/default.rb
vagrant-test/haproxy-ssl/Vagrantfile
vagrant-test/haproxy-ssl/web-dna.json

This still needs to be added (together with `easybib-deploy::ssl-certificates`) to a role to be fully working, but we have to discuss the opsworks setup first.

First working version of haproxy 1.5 with ssl

---

avahi/metadata.rb
avahi/recipes/alias.rb
avahi/recipes/default.rb
easybib/recipes/nscd.rb
easybib/recipes/setup.rb

We'll run into a race condition otherwise if avahi is called before easybib::setup

Bugfix: Use nscd service definition in avahi recipes

---

easybib-deploy/recipes/ssl-certificates.rb
easybib-deploy/spec/ssl-certificates_spec.rb

Also a chefspec to make sure this wont happen again.
Note: There is one Test with a FIXME, since matching Chef::Log.error() does
not work as it is supposed to.

Bugfix: Deploy chained cert also if intermediate ca is empty

---

nginx-app/templates/default/hhvm.conf.erb
nginx-app/templates/default/silex.conf.erb

node['easybib-deploy'] can later be removed from stack.json. already duplicated it to `node['easybib_deploy']`

Bugfix: Typo: It is easybib_deploy in json

---

rsyslogd/files/default/01-fix-timestamp.conf
rsyslogd/recipes/default.rb

There is a known bug in syslog for trusty resulting in weird off timestamps for "compacted" log entries:
This disables compacting
* http://serverfault.com/questions/608690/weird-syslog-order
* http://bugzilla.adiscon.com/show_bug.cgi?id=527

Bugfix: Wrong syslog timestamps

---

.travis.yml

Currently `vendor/*` is added to the tarball for s3, resulting in 150mb cookbooks.

Bugfix: Do not upload vendors to s3

---

nginx-app/recipes/configure.rb

I made some what seems to be minor changes to nginx-app/recipes/configure.rb to support the domain name <-> server_name option in the /etc/nginx/sites-enabled/*.conf files for easybib.com.
I did some tests to see if I could change the conf name and other tests to probe what I can do here.
I also did testing on playground.easybib.com and this appears to work OK.

Easybib nginx changes to support public-api and easybib in plaground

---

nginx-app/templates/default/infolit.conf.erb

search is not used anymore
also should we enable it again than it should be handled via app not separate file

Remove nginx search config for infolit

---

easybib/providers/deploy.rb

Starting supervisord before deployconfig is available results in nasty exceptions

Bugfix: Racecondition with supervisord

---

easybib/providers/crontab.rb
easybib/providers/deploy.rb
easybib/resources/crontab.rb
easybib/spec/easybib_crontab_spec.rb

This way, we always clean up old cronjobs. Otherwise, when we enable the cronjob_role, old cronjobs are not removed

Relocating the decision if crontab deployment is allowed

---

sinopia-github/templates/default/config.yaml.erb

This makes the sinopia-github template read/write by admin & authenticated users only

Tighten sinopia-github access

---

php-fpm/templates/default/php.ini.erb

For whatever random reason, php seems to sometimes just omit `/usr/sbin/sendmail`, 
thus resulting in a broken mail command

Bugfix: Php seems sometimes not do determine sendmail path correct

---

nginx-app/attributes/default.rb
nginx-app/recipes/ppa.rb
php-fpm/attributes/default.rb
redis/attributes/default.rb
redis/recipes/default.rb

* removed an unused ppa attribute
* relocate all easybib::ppa calls to the receipe, so it can be used even if the originating ppa is changed in the node attr

Cleanups with ppa handling

---

supervisor/resources/fcgi.rb
supervisor/resources/service.rb

updates the supervisor default log to syslog for child process logs

set default log to syslog for supervisor 

---

easybib/libraries/easybib.rb
easybib/providers/deploy.rb
easybib/providers/supervisor.rb
easybib/resources/deploy.rb
easybib/resources/supervisor.rb
easybib/tests/test_easybib.rb

https://github.com/easybib/issues/issues/4393
This will allow RabbitMQ consumers to be run only on a single instance.

Only configure supervisor if the instance has supervisor_role

---

easybib-deploy/recipes/silex.rb

references https://github.com/easybib/issues/issues/4429#issuecomment-121266147
Warning: Health check url for id is different, this might cause a downtime if ELB is not adjusted accordingly when updating cookbooks!'

Make id default server for api stack

---

apt/attributes/default.rb
apt/recipes/easybib.rb
aptly/providers/cronjob.rb
easybib/attributes/default.rb
easybib/libraries/ppa.rb
easybib/tests/test_ppa.rb

references https://github.com/easybiblabs/mirror-it/pull/12
This also removes `node[apt][easybib][ppa]` - since we always use the `remote-mirrors` ppa for everything except php, there is now a `node[easybib][php_mirror_version]` version instead. Current default is `55`.

Adapt to new package mirror structure

---

easybib/libraries/helpers.rb
nginx-app/templates/default/scholar.conf.erb

https://github.com/easybib/issues/issues/4620
If the site has any domain names starting with `www.` a 301 redirect will be setup for the non-www version of the domain name.
This has been tested on playground by adding a www. domain to the playground config & deploying the branch.

always redirect iescholar.com to www.iescholar.com

---

easybib/attributes/default.rb

This will blow up attribute merging since we currently use it in easybib and easybib_deploy.
Please note: This fails rubocop, but the failure reason is in the upstream branch, not in the change here.

Reverting bced80e37982783064275654e6a864d2f5236b4a

---

easybib/providers/supervisor.rb

so we can set num_procs (which requires process_name to include
the process_num)
default set to "%(program_name)s", which is supervisord's default
http://supervisord.org/configuration.html

supervisor provider: add process_name config option

---

apache-couchdb/recipes/configure.rb

Asia was having this error:
```
==> web: Recipe Compile Error in /tmp/vagrant-chef/bd4f646c7a6520a257e59062d7313745/cookbooks/scholar/recipes/role-vagrant.rb
```
which I drilled down to:
```
==> web: [2015-09-28T18:30:03+00:00] DEBUG: Loading Recipe apache-couchdb via include_recipe
==> web: [2015-09-28T18:30:03+00:00] DEBUG: Found recipe default in cookbook apache-couchdb
==> web: [2015-09-28T18:30:03+00:00] DEBUG: Loading Recipe apt::ppa via include_recipe
==> web: [2015-09-28T18:30:03+00:00] DEBUG: Found recipe ppa in cookbook apt
==> web: [2015-09-28T18:30:03+00:00] DEBUG: Loading Recipe apache-couchdb::configure via include_recipe
==> web: [2015-09-28T18:30:03+00:00] DEBUG: Found recipe configure in cookbook apache-couchdb
==> web: [2015-09-28T18:30:03+00:00] DEBUG: Loading Recipe …
```

apache-couchdb compile fail during scholar-vagrant web provisioning

---

nginx-app/recipes/service.rb

The awesome `Upstart` hack from @till turned out to be not so awesome after all, unfortunately. The Nginx service is being reloaded gracefully instead of being restarted upon deployment, which effectively brings the entire web-server down.

Force restart of nginx when disabling upstart

---

ies/recipes/cron-mailto.rb
ies/recipes/role-generic.rb

This does no longer work, and also creates an empty cronjob running every minute, spamming the logs

Bugfix: Remove cron-mailto

---

nginx-app/recipes/vagrant.rb

This sometimes can fail in new vagrantenvs when composer was not yet executed.

Fix: Ignore failures for supervisor workers in vagrant

---

redis/recipes/configure.rb

ubuntu package creates /etc/logrotate.d/redis-server, we should overwrite this instead of creating a second one,
which then leads to "duplicate logfile" warning in logrotate

Bugfix: Removes duplicate logrotate

---

apache-couchdb/attributes/default.rb
apache-couchdb/recipes/monitoring.rb
apache-couchdb/spec/monitoring_spec.rb

Since we are now encrypting the credentials in stack json, we can not use those for the monitoring user anymore since we need clear-text passwords in that case. This PR fetches the unencrypted monitoring user credentials from a new `node['apache-couchdb']['monitoring']`setting.
Fixes: https://imagineeasy.atlassian.net/browse/DEVOPS-40

Fix: Use separate monitoring credentials

---

ies/recipes/role-configure.rb

Issue: easybib/issues#5085
---- 
- call ies-route53::add from ies::role-configure
this promises to catch EIP changes and reflect them in our
infrastructure DNS.

Introduce: ies::role-configure

---

php/recipes/module-mysqli.rb
php/spec/module-mysqli_spec.rb

regression from DEVOPS-18: There is no dedicated `php5-easybib-mysqli`, we only configure/enable it

Bugfix: php-mysqli is part of core, needs only config

---

nginx-app/recipes/configure.rb

There is a bug in our current master affecting all instances in `sitescraper` layers. A deprecated `where`-clause hasn't been removed from the `nginx-app::configure` recipe in one of our recent refactorings.

Remove deprecated sitescraper when-clause

---

nginx-app/attributes/default.rb

Changing default access_log from:
default['nginx-app']['access_log'] = 'syslog:server=127.0.0.1:23232'
to:
default['nginx-app']['access_log'] = 'off'
I am leaving default['nginx-app']['access_log'] = 'syslog:server=127.0.0.1:23232' commented out in the default.rb file as a reference.
This will result in the /etc/nginx/sites-enabled/easybib.conf having :
access_log off;
instead of :
access_log syslog:server=127.0.0.1:23232;
This change was necessitated by similar errors to this in syslog:
```
send() to syslog failed while logging request,
client: 10.16.230.125,
server: opsworks.playground.easybib.com,
request: "GET /health_check.php HTTP/1.0",
upstream: "fastcgi://unix:/var/run/php-fpm/pool1"
```
Basically, this issue manifested in many "connection refused" errors.

nginx cannot handle high speed UDP logging ATM

---

stack-service/recipes/role-rabbitmq.rb
vagrant-test/rabbitmq/Vagrantfile
vagrant-test/rabbitmq/test.json

* works with or without logdir set
* a little more robust
* related PR (that broke this): #899
Related: DEVOPS-102

Fix: log dir fubar

---

ies/recipes/opsworks-fixes.rb

Expressed like this, the provider will not throw ugly misleading error messages to the chef log.

Fix /dev/xvdc opsworks-workaround

---

easybib-deploy/recipes/scholar.rb
easybib/providers/nginx.rb
easybib/resources/nginx.rb
nginx-app/recipes/vagrant-silex.rb
nginx-app/recipes/vagrant.rb
stack-academy/recipes/deploy.rb
stack-citationapi/recipes/deploy-vagrant.rb
stack-test/recipes/deploy.rb

* if set, it is set to `deploy/nginx.conf` everywhere
* now acts like the other files in `deploy/`- if file is there, it is used

Streamline: nginx_local_conf is no longer a parameter

---

ies/recipes/opsworks-fixes.rb

The current implementation always overwrites fstab ignoring any local differences, which blows up any instance with EBS volumes mounted

Fix: ies::opsworks-fixes breaks EBS volumes

---

php/providers/ppa_package.rb
php/recipes/module-apc.rb
php/recipes/module-opcache.rb
php/recipes/module-phar.rb
php/recipes/module-xdebug.rb
php/resources/ppa_package.rb
php/spec/fixtures/recipes/php-ppa_package.rb
php/spec/module-opcache_spec.rb
php/spec/module-phar_spec.rb
php/spec/module-xdebug_spec.rb

This PR decouples `php_ppa_package` & `php_config` so we can control what is done with `php_config` directly vs. adding more flags to `php_ppa_package` or accessing `node[]` from within it.
Makes recipes slightly more verbose, but hopefully easier to understand.
Related: DEVOPS-124

Refactor: decouple php_ppa_package & php_config

---

php/attributes/default.rb
php/providers/config.rb
php/recipes/module-apc.rb
php/recipes/module-mysqli.rb
php/recipes/module-opcache.rb
php/recipes/module-phar.rb
php/resources/config.rb
php/spec/fixtures/recipes/php-config.rb
php/spec/provider-config_spec.rb

Make path and suffix attributes to the provider and supply them with default attributes so we don't break the status quo.
Related: DEVOPS-124

Refactor: allow override of file path settings

---

php/recipes/module-tidy.rb

This used to be disabled in the old config: https://github.com/till/easybib-cookbooks/blob/80c8a05cc7adbc7fa1f57522571f0d457788ae1a/php-fpm/templates/default/php.ini.erb#L132 and points to a nonexisting file

Fix: Remove errorneous config path

---

stack-easybib/attributes/default.rb
stack-easybib/recipes/deploy-easybib.rb

This PR introduces the ability to disable logging of 404 errors in the nginx error-log.
- Node: node['easybib']['nginx-app']['disable-404']
- Type: bool
- Default: false

Ability to disable logging of 404 in stack-easybib

---

php-fpm/templates/default/php.ini.erb

number is arbitrary, but lower than the default (100k) - tested on the easybib VM and seems to help

set pcre recursion limit

---

stack-easybib/templates/default/easybib.com.conf.erb

When I was working on a solution for https://github.com/easybib/sbm-issues/issues/359 I added a /deploy/nginx.conf and found that it was not added to the nginx/sites-enabled/[appname].conf template.  This is a quick fix to add that rendering.

Add of local config support for easybib stack template

---

easybib/providers/nginx.rb
easybib/resources/nginx.rb
nginx-app/attributes/default.rb
nginx-app/templates/default/partials/php-routes-default.erb
nginx-app/templates/default/scholar.conf.erb
nginx-app/templates/default/silex.conf.erb
nginx-app/tests/test_helpers.rb
stack-citationapi/templates/default/default-web-nginx.conf.erb

we are using `cache_config` at some points for browser config, others for nginx config - this gets confusing, so I changed it.
fixes DEVOPS-157

Fix: Variable name collision

---

easybib/libraries/config.rb

The ``DATABASE_URL`` is a environment variable used e.g. in the Ruby ecosystem. It is a composite of all DB details in form of a URL like this:
```
mysql2://user:password@host:port/database?reconnect=true
```
This patch creates that variable in case that all necessary parts are set in the DB config.

Adds DATABASE_URL to app's environment

---

haproxy/templates/default/haproxy.cfg.backend.erb
haproxy/templates/default/haproxy.cfg.forwardingbackend.erb
haproxy/templates/default/haproxy.cfg.globals.erb
haproxy/templates/default/haproxy.cfg.websocketbackend.erb

* prep for more let's encrypt work
* forwardfor: add x-forwarded-for header
* http-server-close:
* close connections between user and haproxy
* maintain keep-alive
* remove redunant option in backend (matched global)
Related: DEVOPS-163

Change: update options

---

cron/libraries/matchers.rb

Couldn't build a test with `cron_d`, so I fixed it.
Now sleep. 💤

Fix: cron_d matcher is incomplete

---

ies-route53/libraries/helper.rb
ies-route53/providers/record.rb
ies-route53/recipes/add.rb
ies-route53/resources/record.rb
ies-route53/spec/add_spec.rb

This can be discovered using the instance role when required
and saves us from having yet another IAM user that is setup
in order to do something in Chef.
* Setup an instance profile on the new sparkle notebook playground.
* Assign profile rights to access:
* Route53 (see specific zone_id in custom json)
* S3 (just for completeness)
* start stack, check if A record is created

Update: allow empty credentials

---

nginx-app/recipes/vagrant-silex.rb
stack-easybib/recipes/deploy-webapps-vagrant.rb

https://github.com/easybib/sbm-issues/issues/524
Make sure that SQS workers inside vagrant are run as www (same as playground/production) and not edu

Easybib: run workers as www not edu in vagrant

---

stack-citationapi/recipes/role-citation-pdf-api.rb
stack-citationapi/spec/role-citation-pdf-api_spec.rb

Jira: https://imagineeasy.atlassian.net/browse/DEVOPS-168
----
A chat with @appmode just made clear that the local Gearmand is really only needed on the Vagrant box.

Deploy local Gearmand only on Vagrant

---

stack-citationapi/recipes/deploy-citationapi.rb

Jira: https://imagineeasy.atlassian.net/browse/DEVOPS-168
@appmode just noticed a bug where FPM is not reloaded after deployment of PDF-Autocite. Here is the fix.

Reload FPM after deploying PDF-Autocite

---

.travis.yml
MoveBerkshelfArtifacts.sh

Refers to https://github.com/easybib/ops/issues/169
* add call to a shell script to MoveBerkshelfArtifacts.sh 
* create MoveBerkshelfArtifacts.sh which just moves and renames them to `build/artifact-_container_.tar.gz`

Publish Berkshelf artefacts to S3 #169

---

easybib/libraries/config.rb
stack-cmbm/attributes/default.rb
stack-cmbm/recipes/deploy-nginxapp.rb

Issue: easybib/ops#186
This PR prepares our cookbooks for a vital change in CMBM that is currently causing old puma instances to not be torn down correctly during app redeployments.

CMBM: Cleanup old puma procs on app redeployment

---

easybib-deploy/attributes/default.rb
easybib-deploy/recipes/easybib.rb
easybib-deploy/recipes/qa.rb
easybib-deploy/recipes/silex.rb
easybib/attributes/default.rb
easybib/providers/deploy_manager.rb
stack-citationapi/recipes/deploy-citationapi.rb
stack-easybib/recipes/deploy-easybib.rb
stack-easybib/recipes/deploy-silexapps.rb
stack-research/recipes/deploy-research.rb
stack-test/recipes/deploy.rb

This PR replaces all occurrences of `node[easybib-deploy]` with `node[easybib_deploy]` (note: the underscore). See easybib/ops#15.
Please merge to master **AFTER** the next stable merge to win us enough time for stabilization.

Cleanup node[easybib-deploy]

---

MoveBerkshelfArtifacts.sh

- don't use sh syntax in Bash
- create missing directories
- never use the output of ls in for loops (http://mywiki.wooledge.org/ParsingLs)
- always quote path variables

Improve MoveBerkshelfArtifacts.sh

---

stack-cmbm/recipes/role-vagrant.rb
stack-cmbm/spec/role-vagrant_spec.rb

This PR installs the package `xvfb` to the CMBM Vagrant box. The package is needed for testing.
Related: easybib/ops#197

Install xvfb into CMBM vagrant box

---

easybib/libraries/config.rb
stack-cmbm/recipes/deploy-nginxapp.rb
stack-cmbm/templates/default/default-web-nginx.conf.erb

The new rundir settings were broken:
* nginx was not at all aware of the new ones
* the deploy recipe only respected the app specific one
Since there is no use case currently for the app specific path, I opted to migrate everything to the global config, and clean things up.
Already tested on cm in opsworks, works.

Make nginx aware of the new rundir, remove second param storage

---

stack-cmbm/recipes/deploy-nginxapp.rb

Fork Puma directly under supervisor to prevent orphaned child processes when supervisor reloads and/or restarts.
P.S.: Additionally grant Puma at least one second to start up as zero doesn't seem to make sense and all our other stacks have one second configured, as well.
- Test by redeploying the CM or BM application in playground and note how they stay available.
Related: easybib/ops#186

Reload supervisor to fix stale Puma instances

---

stack-easybib/recipes/role-phpapp.rb

`stack-easybib` requires supervisor. It is even stated in `metadata.rb` however not included anywhere beneath `stack-easybib::role-phpapp`. This PR includes supervisor so it is actually available when other cookbooks try to use it.
- Deploy an nginxapp instance in stack-easybib PG and notice how it doesn't fail due to missing `supervisorctl`.
Related: easybib/ops#202

Easybib depends on supervisor; pull it in

---

stack-cmbm/recipes/deploy-vagrant.rb

We have been seeing problems with supervisor not managing puma correctly. Beforehand, we spawned puma using a small Bash helper (which ensured the correct environment). This leads to the fact, that supervisor in fact manages the Bash child and the kernel moving the actual puma processes under Init when the parent Bash died (standard Linux behaviour of unparented processes).
I prepared a fix last week, but didn't consider that this also happens in Vagrant, as well.
This PR makes sure that Puma is always the direct child of the supervisor process in CMBM vagrant box.
This PR only leads to a working result if https://github.com/easybib/citationmachine-bibme/pull/1207 is also merged.
- Spin up the Vagrant box of CMBM and issue `supervisorctl restart all`. Not how the puma processes restart …

Fix puma+supervisor setup in Vagrant

---

ies-letsencrypt/templates/default/certbot-cronjob.sh.erb
nginx-app/templates/default/redirect-ssl.conf.erb

Bugfix: cron script only supported haproxy before
Related: easybib/ops#207

Fix: nginx reload after cert update

---

tideways/metadata.rb
tideways/recipes/configure.rb
vagrant-test/php/Vagrantfile

Fixes `tideways-php` to work with ondreij's PPA. 
* symlink .so's into all directories
* ensure .ini files get installed into all dirs (using `phpenmod`)
- I ran `vagrant-test/php` and `php -m` contained tideways
Related: #1119

Fix: fix tideways install with ondreij php

---

ies-sinopia/README.md
ies-sinopia/metadata.rb
ies-sinopia/recipes/default.rb
ies-sinopia/recipes/users.rb
ies-sinopia/spec/default_spec.rb
ies-sinopia/spec/spec_helper.rb
ies-sinopia/spec/users_spec.rb

This PR scales-out our changes to the upstream `Sinopia` cookbook into `ies-sinopia`.
Related: easybib/ops#213

Scale-out of Sinopia Cookbook

---

php-fpm/recipes/service.rb

Provider on 14.04 is not `Init`, we fall back to the Chef default (which worked before).

Fix: provider used does not work on 14.04

---

php/recipes/dependencies-ppa.rb

This is to prevent instances from calling Ubuntu's keyserver
which is notoriously unstable. :shit:
Uses the keys contained within the `aptly` cookbook. Not ideal
but it should work.
- pull this PR, `cd autocite && vagrant up`
Related: easybib/ops#235

Fix: supply 'local' key to apt_repository

---

easybib/attributes/default.rb
easybib/providers/deploy.rb
easybib/providers/gearmanw.rb
easybib/resources/deploy.rb
easybib/resources/gearmanw.rb
easybib/spec/easybib_gearmanw_spec.rb
easybib/spec/fixtures/recipes/easybib_gearmanw.rb
pecl-manager/README.md
pecl-manager/providers/script.rb
pecl-manager/recipes/vagrant.rb
pecl-manager/resources/script.rb
pecl-manager/templates/default/init.d.erb

Removes the `envvar_json_source` for the gearman setup. We used to use this with getcourse, but it nowadays is nowhere in use.
Any new use case should respect the `.deploy_configuration` mechanism anyway.

Cleanup: Remove envvar_json_source

---

easybib/libraries/deploy.rb
easybib/providers/crontab.rb
easybib/providers/deploy.rb
easybib/resources/crontab.rb
easybib/resources/deploy.rb
easybib/tests/test_crontab_provider.rb
easybib/tests/test_deploy.rb

Also relocates cronjob related functions from shared lib to cronjob provider

Refactoring: Remove cronjob_role param - nowhere used

---

easybib/providers/deploy.rb
easybib/providers/deploy_manager.rb
easybib/resources/deploy.rb
stack-api/recipes/deploy-silex.rb
stack-citationapi/recipes/deploy-citationapi.rb
stack-cmbm/recipes/deploy-nginxapp.rb
stack-easybib/recipes/deploy-easybib.rb
stack-easybib/recipes/deploy-gearman-worker.rb
stack-easybib/recipes/deploy-housekeeping.rb
stack-easybib/recipes/deploy-silexapps.rb
stack-fruitkid/recipes/deploy-easybib.rb
stack-qa/recipes/deploy-qa.rb
stack-qa/recipes/deploy-satis.rb
stack-research/recipes/deploy-research.rb
stack-research/recipes/deploy-solr.rb
stack-test/recipes/deploy.rb

The application name is already passed everywhere as name anyway.
Also removes two parameters that are obsolete and nowhere in use.
ref https://github.com/easybib/ops/issues/233

Cleanup: Remove redundant application parameter

---

easybib/providers/nginx.rb
easybib/resources/nginx.rb

* We never supply a different `config_name` anywhere, so we always fall back to application name anyway
* nginx caching is always configured using stack json attributes, never as a parameter
https://github.com/easybib/ops/issues/233

Cleanups: Remove parameters we never supply anywhere

---

easybib/README.md
easybib/attributes/default.rb
easybib/providers/crontab.rb
easybib/providers/deploy.rb
easybib/resources/crontab.rb
ies/recipes/role-undeploy.rb

Removing redundant parameter, removed broken cronjob user parameter
The cronjob user parameter was entirely messed, and the parameter is actually only used in the `delete` action.  During creation, `node['nginx-app']['user']` is used as the user parameter in the code, so I standardized to that one.
https://github.com/easybib/ops/issues/233

Cleaning up easybib_crontab

---

easybib/resources/crontab.rb

Currently the app name for cronjobs is always empty, since the default always overrides the name attribute.

Fix: default and name-attribute dont work together

---

stack-easybib/files/default/rds-test.sh
stack-easybib/recipes/deploy-rdstest.rb
stack-easybib/recipes/role-nginxphpapp.rb

As of this PR we deploy a PHP script for testing RDS connection round-trips to every nginxapp instance in stack-easybib. The script is deployed in form of an AWS OpsWorks app and comes with a small shell script that iteratively curl's localhost and writes the response to a log-file.
Related: easybib/ops#226

Deploy rds-test script to nginxapp instances

---

stack-qa/recipes/deploy-qa.rb

The call is somewhat redundant, since [it is being done in easybib_deploy anyway](https://github.com/till/easybib-cookbooks/blob/master/easybib/providers/deploy.rb#L14-L18)
This way, all `opsworks_*` calls for a deploy are now entirely wrapped within `easybib_deploy`, which makes the chef12 migration easier
references https://github.com/easybib/ops/issues/233

Remove opsworks_deploy_dir - this is unneeded

---

Rakefile
foodcritic-rules.rb

Since node[deploy], node[opsworks] and opsworks_* will be gone in Chef12, we are relocating everything using this in easybib_deploy, easybib/libraries/* and the wt-data cookbook so that we then have one single point for each case we have to readjust for Chef12.
WT003, the disabling of `node[deploy]` is disabled currently, this need some more changes in the cookbooks.
Related: https://github.com/easybib/ops/issues/233

Introduce custom foodcritic rules for Chef12 prep

---

tideways/attributes/default.rb
tideways/recipes/default.rb

Ensures only certain versions are installed, so new packages don't break our setup.
- test in `www-vagrant`
- test on playground
Related: easybib/ops#251

Fix: set an explicit version for tideways packages

---

php/attributes/default.rb
php/recipes/module-sybase.rb
php/spec/module-sybase_spec.rb
php/templates/default/freetds.erb
stack-easybib/recipes/role-vagrant.rb

Adds support for `php5-sybase` (and freetds) to allow PHP to talk to MS SQL Server. Only works when a stack is on ondrej PPA.
Related: easybib/sbm-issues#841

Enhancement: support for MS SQL Server

---

stack-easybib/recipes/deploy-rdstest.rb

The `deploy-rdstest` recipe lacks a few dependencies. These where available by incident in earlier tests, probably because other apps have been installed on the instance that pulled those dependencies in.
Related: easybib/ops#226

[WIP] RDS Test additions

---

stack-qa/recipes/deploy-redirector.rb
stack-qa/spec/deploy_redirector_spec.rb
stack-qa/templates/default/redirect-certbot.conf.erb
stack-qa/templates/default/redirect-ssl.conf.erb

This PR fixes the broken redirector setup described in easybib/ops#242.
The problem was, that several vHost configuration files where rendered to disk, all containing a `default_server` directive, which validates Nginx configuration syntax.
This PR renders a single vHost configuration file to disk and then redirects based on `$host`.
It is commonly known that if-statements in Nginx configuration are evil. This is true! However, rewrites are an exception to the rule. See: https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/
- Specs are included in the change.
Related: easybib/ops#242

Render all LetsEncrypt rewrites into a single vHost

---

stack-api/recipes/role-nginxphpapp.rb
stack-api/spec/role-nginxphpapp_spec.rb

This PR runs the `install_package` matcher against every PHP module we have installed in production.
It also completes the list of missing PHP modules in the recipe.
- `bundle exec appraisal rake 'spec[stack-api]'`
Related: easybib/ops#259

Add missing php modules and tests

---

php-fpm/recipes/default.rb
php-fpm/spec/default_spec.rb

PHP by default installs a session-cleanup cron-job which is triggering a PHP warning to be sent out to sysops@ every 30mins. We do not need this cron-job because all our sessions are stored in memcache.
With this PR the cron-job will be deleted automatically upon installation of `php-fpm`.
- RSpecs included
Related: easybib/ops#272

[WIP] Delete the PHP sessionclean cronjob

---

ies-gearmand/recipes/service.rb
php/attributes/default.rb
php/recipes/module-gearman.rb

Added New PPA to php:module-gearman per https://www.patreon.com/posts/gearman-now-in-14627464
This solved the gearmand8 issue with package installation.
however this caused a problem with the gearman-job-server restart... I think because /etc/init/gearman-job-server.conf was missing and only override existed?  
I am not sure if this is the proper fix.  or if conf and override should both exist?
Related: OPS-14646

Gearman PPA has changed

---

ies-gearmand/recipes/service.rb

creates /etc/init/gearmand.conf if missing 
- _(if applicable) how to test them_
Related: #issue

Add gearman conf if missing

---

ies/recipes/role-phpapp.rb
php/attributes/default.rb
php/recipes/module-gearman.rb
stack-citationapi/recipes/role-phpapp.rb

Ensures we use the recipe to install ext/gearman since it requires multiple
apt repositories to be discovered.
For: OPS-15045

Adresses phpX.Y-gearman installation issues

---

haproxy/spec/backend_forwarding-http-set-path_spec.rb
haproxy/templates/default/haproxy.cfg.forwardingbackend.erb
haproxy/templates/default/haproxy.easybib.cfg.erb

- Support for `http-request set-path` in the backend definition for forwarding_layers configuration (new attribute is `http_set_path`)
- modify spec test for existance of `http_set_path` and proper backend definition
- modify spec test for NOT existance of `http_set_path`
- _(if applicable) how to test them_
Related: https://github.com/easybib/sbm-issues/issues/2182

Support for force set-path for forwarding_layer configuration

---

haproxy/templates/default/haproxy.cfg.forwardingbackend.erb

using regex `reqirep  ^([^\ :]*)\ /(.*) \1\ <%= @http_set_path %>\2` instead of `http-request set-path <%= @http_set_path %>`
- _(if applicable) how to test them_
Related: #issue

HAPROXY: Fix for http-request set-path not suppported below v1.6

---

haproxy/spec/backend_forwarding-http-set-path_spec.rb
haproxy/templates/default/haproxy.cfg.forwardingbackend.erb
haproxy/templates/default/haproxy.easybib.cfg.erb

Specific header changes for S3 - this should be expanded upon to be more extensible
now assuming static path match with static path replace
```
"forwarding_layers": {
"adstxt":{  
"acl":{  
"acl-10":"path_beg /ads.txt"
},
"http_match_path":"ads.txt",
"http_set_path":"/adteam-adtxt/easybib.com/ads.txt",
"http_set_host":"s3.amazonaws.com",
"haproxy_check_interval":"10m",
"health_check":"GET /adteam-adtxt/easybib.com/ads.txt HTTP/1.1\\r\\nHost:\\ s3.amazonaws.com",
"servers":{  
"s3_adteam":"s3.amazonaws.com"
}
},
```
becomes
```
backend adstxt_forward
balance roundrobin
http-request set-header Host s3.amazonaws.com
http-request del-header Authorization
reqirep ^([^\ ]*)\ /ads.txt\ (.*)$ \1\ /adteam-adtxt/easybib.com/ads.txt\ \2
option httpchk GET /adteam-adtxt/easybib.com/ads.txt …
```

Fixes for s3
